# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-alpine

# Set working directory
WORKDIR /app

# Install system dependencies: add gcc, g++, musl-dev, linux-headers
RUN apk add --no-cache gcc g++ musl-dev linux-headers

# Copy project files
COPY . /app

# Install Python dependencies
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

# Set default environment variables (can be overridden)
ENV SNOWFLAKE_USER=your_username \
    SNOWFLAKE_PASSWORD=your_password \
    SNOWFLAKE_ACCOUNT=your_account \
    SNOWFLAKE_DATABASE=your_database \
    SNOWFLAKE_WAREHOUSE=your_warehouse

# Command to run the MCP server
CMD ["python", "server.py"]
